<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sys" name="TmpTest" tests="3" failures="2" timestamp="21 Jun 2015 11:20:47 GMT" time="1.072" errors="0">
  <testcase name="testCase1" time="1.047" classname="com.example.testCases.TestCase01"/>
  <testcase name="testCase2" time="0.003" classname="com.example.testCases.TestCase01">
    <failure type="java.lang.AssertionError" message="Assert Failed Message">
      <![CDATA[java.lang.AssertionError: Assert Failed Message
	at com.example.utils.CustomListner.onTestFailure(CustomListner.java:15)
	at com.example.utils.Driver.main(Driver.java:41)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.001" classname="com.example.testCases.TestCase01">
    <failure type="java.lang.AssertionError" message="Assert Failed Message - TestCase 3">
      <![CDATA[java.lang.AssertionError: Assert Failed Message - TestCase 3
	at com.example.utils.CustomListner.onTestFailure(CustomListner.java:15)
	at com.example.utils.Driver.main(Driver.java:41)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- TmpTest -->
